# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

  build:
    runs-on: ubuntu-latest
    needs: check
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      # build default locale zh and deploy
      - name: Run yarn build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Deploy Default Locale zh
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: "/docker/app/nginxWebUI/www/docs.ikaros.run"

      # # build en locale and deploy
      # - name: Run yarn build --locale en
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: build --locale en

      # - name: Deploy Default Locale zh
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #     ARGS: "-avzr --delete"
      #     SOURCE: "build/"
      #     REMOTE_HOST: ${{ secrets.SERVER_HOST }}
      #     REMOTE_PORT: ${{ secrets.SERVER_PORT }}
      #     REMOTE_USER: ${{ secrets.SERVER_USER }}
      #     TARGET: "/docker/app/nginxWebUI/www/docs.ikaros.run/en"

      # # build jp locale and deploy
      # - name: Run yarn build --locale jp
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: build --locale jp

      # - name: Deploy Default Locale zh
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #     ARGS: "-avzr --delete"
      #     SOURCE: "build/"
      #     REMOTE_HOST: ${{ secrets.SERVER_HOST }}
      #     REMOTE_PORT: ${{ secrets.SERVER_PORT }}
      #     REMOTE_USER: ${{ secrets.SERVER_USER }}
      #     TARGET: "/docker/app/nginxWebUI/www/docs.ikaros.run/jp"
